version: "3.9"

services:
  #api:
  #  image: pigges/lbry-api
  #  ports:
  #    - 3000:8080
  #  #depends_on:
  #  #  - lbrynet
  #  environment:
  #    API_NAME: "1"
  #  networks:
  #    - net
  #lbrynet:
  #  image: odyseeteam/lbrynet-tv:0.110.0
  #  container_name: lbrynet
  #  environment:
  #    SDK_CONFIG: /config/daemon_settings_docker.yml
  #  networks:
  #    - net
  #  volumes:
  #    - storage:/storage
  #    - ./daemon:/config

networks:
  net:

volumes:
  storage: {}